using System.Net;
using System.Security.Claims;
using System.Text.Json;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OAuth;
using Microsoft.AspNetCore.HttpOverrides;

var builder = WebApplication.CreateBuilder(args);

// These credentials come from the local user-secrets store rather than source-controlled configuration.
// The client ID identifies the Discord application and the client secret authenticates this server to Discord.
var discordClientId = builder.Configuration["Discord:ClientId"];
var discordClientSecret = builder.Configuration["Discord:ClientSecret"];

// The shared template lets this sample keep protocol code separate from display markup.
var pageTemplate = File.ReadAllText(Path.Combine(builder.Environment.ContentRootPath, "PageTemplate.html"));
var useForwardedHeaders = builder.Configuration.GetValue<bool>("ReverseProxy:UseForwardedHeaders");

// The cookie handler becomes this application's local session mechanism. It stores the claims created
// after Discord authentication so later requests do not need to redirect to Discord again.
// The OAuth handler performs the remote OAuth protocol and then signs in through this cookie handler.
builder.Services
    .AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie()

    // This registers ASP.NET Core's OAuth authentication handler under the "Discord" scheme. From this
    // point, the framework owns the authorization redirect, state and PKCE protection, callback processing,
    // code-for-token exchange, and sign-in to the cookie scheme configured above.
    .AddOAuth("Discord", options =>
    {
        // Placeholder values let the home page load before configuration; /login detects the real mistake.
        options.ClientId = string.IsNullOrWhiteSpace(discordClientId) ? "not-configured" : discordClientId;
        options.ClientSecret = string.IsNullOrWhiteSpace(discordClientSecret) ? "not-configured" : discordClientSecret;

        // Discord redirects the browser to this client application's backend callback after approval. This
        // localhost process simulates the cloud service that would own this endpoint in production. The OAuth
        // handler intercepts the path before MapGet endpoints, verifies protected state, and processes the code.
        // In production, register the exact public HTTPS callback URI. If a reverse proxy terminates TLS,
        // it must forward the original scheme and host so this handler generates that public URI.
        options.CallbackPath = "/auth/callback";
        options.AuthorizationEndpoint = "https://discord.com/api/oauth2/authorize";
        options.TokenEndpoint = "https://discord.com/api/oauth2/token";
        options.UserInformationEndpoint = "https://discord.com/api/users/@me";

        // PKCE binds the authorization code to a verifier generated by the middleware, making a stolen code
        // unusable without that verifier. The manual demo shows the equivalent code explicitly.
        options.UsePkce = true;

        // identify is the minimum Discord scope needed to call /users/@me.
        options.Scope.Add("identify");

        // Map selected fields from Discord's /users/@me JSON response into local identity claims.
        options.ClaimActions.MapJsonKey(ClaimTypes.NameIdentifier, "id");
        options.ClaimActions.MapJsonKey(ClaimTypes.Name, "username");
        options.ClaimActions.MapJsonKey("urn:discord:global_name", "global_name");

        // OAuthEvents are the handler's extension points. They expose selected moments in the framework-run flow
        // without requiring this application to reimplement the protocol.
        options.Events = new OAuthEvents
        {
            OnCreatingTicket = async context =>
            {
                // The handler already validated state and exchanged the authorization code for tokens before
                // this event. Fetch the Discord profile with its access token, then apply the mappings above.
                using var request = new HttpRequestMessage(HttpMethod.Get, context.Options.UserInformationEndpoint);
                request.Headers.Authorization = new("Bearer", context.AccessToken);

                using var response = await context.Backchannel.SendAsync(
                    request,
                    HttpCompletionOption.ResponseHeadersRead,
                    context.HttpContext.RequestAborted);
                response.EnsureSuccessStatusCode();

                // RequestAborted stops the network operation if the browser disconnects before it completes.
                await using var stream = await response.Content.ReadAsStreamAsync(context.HttpContext.RequestAborted);
                using var user = await JsonDocument.ParseAsync(stream, cancellationToken: context.HttpContext.RequestAborted);
                context.RunClaimActions(user.RootElement);

                context.HttpContext.RequestServices
                    .GetRequiredService<ILoggerFactory>()
                    .CreateLogger("DiscordOAuth")
                    .LogInformation(
                    "Discord OAuth callback invoked for Discord user {DiscordUserId}.",
                    user.RootElement.GetProperty("id").GetString());
            },
            OnTicketReceived = context =>
            {
                // This runs after remote authentication creates the ticket but before the handler writes the
                // local cookie. It is useful for inspecting or changing the ticket before sign-in completes.
                context.HttpContext.RequestServices
                    .GetRequiredService<ILoggerFactory>()
                    .CreateLogger("DiscordOAuth")
                    .LogInformation("Discord OAuth callback completed successfully.");
                return Task.CompletedTask;
            },
            OnRemoteFailure = context =>
            {
                // Provider denials and state-validation failures also arrive at CallbackPath. Handle the response
                // so the default remote-authentication error page is not written after this friendly redirect.
                context.HttpContext.RequestServices
                    .GetRequiredService<ILoggerFactory>()
                    .CreateLogger("DiscordOAuth")
                    .LogWarning(context.Failure, "Discord OAuth callback failed.");
                context.Response.Redirect("/?error=Discord%20sign-in%20failed.%20See%20the%20server%20log%20for%20details.");
                context.HandleResponse();
                return Task.CompletedTask;
            }
        };
    });

var app = builder.Build();

if (useForwardedHeaders)
{
    // A production reverse proxy often terminates HTTPS before forwarding to ASP.NET Core. Process its trusted
    // X-Forwarded headers before HTTPS redirection and OAuth so callback URLs use the public scheme and host.
    // Configure KnownProxies or KnownNetworks for the deployment before enabling this setting.
    app.UseForwardedHeaders(new ForwardedHeadersOptions
    {
        ForwardedHeaders = ForwardedHeaders.XForwardedFor |
                           ForwardedHeaders.XForwardedHost |
                           ForwardedHeaders.XForwardedProto
    });
}

// Authorization codes, session cookies, and access tokens must not travel over plain HTTP.
app.UseHttpsRedirection();

// This activates ASP.NET Core authentication middleware. For a normal request, it reads the local cookie and
// assigns its ClaimsPrincipal to HttpContext.User. For /auth/callback, it dispatches to the registered Discord
// OAuth handler before endpoint routing, which is why this project does not have MapGet("/auth/callback").
app.UseAuthentication();

app.MapGet("/", (HttpContext context) =>
{
    var error = context.Request.Query["error"].FirstOrDefault();
    var message = error is null ? string.Empty : $"<p class=\"error\">{WebUtility.HtmlEncode(error)}</p>";
    var body = context.User.Identity?.IsAuthenticated == true
        ? "<p>You are signed in. The Discord callback ran and created this local authentication cookie.</p><p><a href=\"/callback-complete\">View callback result</a> or <a href=\"/logout\">sign out</a>.</p>"
        : "<p>Click the button to sign in using Discord.</p><p><a class=\"button\" href=\"/login\">Sign in with Discord</a></p>";

    return Results.Content(Page("Discord OAuth demo", $"{message}{body}"), "text/html");
});

app.MapGet("/login", (HttpContext context) =>
{
    // Fail before redirecting if secrets were not configured, so setup mistakes are obvious.
    if (string.IsNullOrWhiteSpace(discordClientId) ||
        string.IsNullOrWhiteSpace(discordClientSecret))
    {
        return Results.BadRequest("Set Discord:ClientId and Discord:ClientSecret with dotnet user-secrets first.");
    }

    // Challenge delegates the protocol to the registered Discord handler. It creates protected correlation and
    // state values, generates PKCE data, and redirects to Discord's authorization endpoint. After processing
    // /auth/callback, the handler redirects to this local result page rather than exposing a callback endpoint.
    return Results.Challenge(
        new AuthenticationProperties { RedirectUri = "/callback-complete" },
        authenticationSchemes: ["Discord"]);
});

app.MapGet("/callback-complete", (HttpContext context) =>
{
    if (context.User.Identity?.IsAuthenticated != true)
    {
        return Results.Redirect("/");
    }

    // Claims originated with Discord. HTML-encode both fields before adding them to this demonstration table.
    var claims = string.Join(
        Environment.NewLine,
        context.User.Claims.Select(claim =>
            $"<tr><td>{WebUtility.HtmlEncode(claim.Type)}</td><td>{WebUtility.HtmlEncode(claim.Value)}</td></tr>"));

    return Results.Content(
        Page(
            "OAuth callback completed",
            "<p>The browser returned to <code>/auth/callback</code>. ASP.NET Core validated <code>state</code>, exchanged the authorization code for tokens, called Discord's user endpoint, and created the cookie shown below.</p>" +
            $"<table><thead><tr><th>Claim type</th><th>Claim value</th></tr></thead><tbody>{claims}</tbody></table><p><a href=\"/\">Home</a></p>"),
        "text/html");
});

app.MapGet("/logout", async (HttpContext context) =>
{
    // This removes only this application's cookie. It does not sign the person out of Discord itself.
    await context.SignOutAsync();
    return Results.Redirect("/");
});

app.Run();

string Page(string title, string body) =>
    pageTemplate
        .Replace("{{title}}", WebUtility.HtmlEncode(title))
        .Replace("{{body}}", body);
